= Leo Code
Christian Donnabauer
1.0, 2020-06-21
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

Following file only serves as a quick overview of the repository. You
can find more specific documentation about each child directory and its purpose
in additional README.adoc files, located in the corresponding directories.

If interested maybe also have a look at the documentation-only repository ->
https://github.com/donnabauerc/LeoCodeDocs

== Structure of the Repo
So the structure of the repository is pretty basic. In the backend directory you can find everything related to the
backend e.g. a Quarkus Server => same thing for the testing-api directory.

In the testing directory you find two subdirectories http-requests & simulating files. In the http-requests directory
there is the requests.http file, which uses the other files located in the simulating-files directory for a h
ttp-request.

== Setup
To run the project yourself follow these steps:

* Prerequisites:
** Docker
** jdk/maven
* Clone the Repository
* Open a command line and go to the `testing-api` directory
* In said directory type: `mvn package` => is "required" for Docker
* After the build finished go to the root directory of the repository
* Simply type: `docker-compose up` and docker should do its magic (don't worry may take quite a bit)

== Demonstration
To get a better insight on how the project works you can test a pre-configured example with following steps:

* First go a setup the project, then start the Docker Containers e.g. `docker-compose up`
* Then navigate into the `testing/http-requests` directory and open the `requests.http` File
* The file contains 2 requests. One for creating an example and one for testing. Either run the first request e.g.
`Create Example` and the second e.g. `Test your Code` after, or simply run the whole file.