= Leo Code
Christian Donnabauer
1.0, 2020-06-21
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

Following file only serves as a quick overview of the repository. You
can find more specific documentation about each child directory and its purpose
in additional README.adoc files, located in the corresponding directories.

If interested maybe also have a look at the documentation-only repository ->
https://github.com/donnabauerc/LeoCodeDocs

== Structure of the Repo
So the structure of the repository is pretty basic. In the backend directory you can find everything related to the
backend e.g. a Quarkus Server => same thing for the other directory.

== Setup
To run the project yourself follow these steps:

* Prerequesites:
** Docker
** jdk/maven
* Clone the Repository
* Open a command line and go to the `testing-api` directory
* In said directory type: `mvn package` => is "required" for Docker
* After the build finished go to the root directory of the repository
* Simply type: `docker-compose up` and docker should do its magic (don't worry may take quite a bit)
