= Leo Code
Christian Donnabauer
1.0, 2020-06-21
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

Following file only serves as a quick overview of the repository. You
should find more specific documentation about each child directory and its purpose
in additional README files, located in the corresponding directories.

If interested maybe also have a look at the documentation-only repository ->
https://github.com/donnabauerc/LeoCodeDocs

== Structure of the Repo
* In the **backend** directory you can find everything related to the backend e.g. a Quarkus
Server. This Quarkus Instances main purpose is communicating with the database. It also
creates .zip Archives and sends a Kafka Message, if a student wants to test his code.

* The **testing-api** directory contains the Quarkus Instance, which is responsible for
Testing Projects. It listens to Kafka Messages and if triggered, tests(unzips, creates
Project Structure, starts Jenkins) and returns a Kafka Message with the result.

* The directory **http-requests** is used for testing. If you want to run the project
yourself, you can use the HTTP files to run a sample project-sequence. In the subdirectory
**simulating-files** sample files for testing are already provided.

== Run yourself
Since until now I haven't dockerized this version you need to setup some stuff, in order to
run the project:

=== Setup
* You will need: JDK(8 or 11), Maven, wget, unzip

WARNING: I recently set up a local Jenkins and couldn't get it to work under JDK 11 only a
downgrade to JDK 8 seemed to fix the issues (e.g. installing the recommended jenkins plugins
correct). Which is strange because JDK 11 is explicitly mentioned on the official Jenkins
Website to work too.

* Install Local Jenkins:

** `wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war` - download the latest war
file of jJenkins

** `unzip jenkins.war -d /opt/jenkins` - extract Jenkins

** `JENKINS_HOME=/opt/jenkins_home java -jar jenkins.war` - set Jenkins Home & run Jenkins

** go to http://localhost:8080/ , follow the installation step & install the recommended set
of plugins

** install the https://plugins.jenkins.io/docker-workflow/[Docker Pipeline] Plugin
(Manage/Jenkins/Plugins ...)

* Install Jenkins-Runner:

** `wget https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile
-runner/1.0-beta-18/jenkinsfile-runner-1.0-beta-18.zip` - download the Jenkins-Runner zip file

** `unzip jenkinsfile-runner-1.0-beta-18.zip -d /opt/jenkinsfile-runner` - unzip the
Jenkins-Runner

** `sudo chmod +x /opt/jenkinsfile-runner/bin/jenkinsfile-runner` make executable

=== Run

1. Start the postgres database & Kafka Broker via Docker compose. In the project root type
`docker-compose up`

2. Start the quarkus servers: go into the `backend` / `testing-api` directory and start them
by typing `./mvnw clean compile quarkus:dev`

Then you can run the requests.http file located in testing/http-requests but be sure to use
the right ID, which can be found in the database.

Import Database into Intellij with the `backend/datasource.txt` file
=> go into IntelliJ open `Database/Import from Clipboard`, User: app Password: app