= Leo Code
Christian Donnabauer
1.0, 2020-06-21
ifndef::imagesdir[:imagesdir: images]
:icons: font
:toc: left

Following file only serves as a quick overview of the repository. You
should find more specific documentation about each child directory and its purpose
in additional README.adoc files, located in the corresponding directories.

If interested maybe also have a look at the documentation-only repository ->
https://github.com/donnabauerc/LeoCodeDocs

== Structure of the Repo
So the structure of the repository is pretty basic. In the backend directory you can find everything related to the
backend e.g. a Quarkus Server => same thing for the testing-api directory.

== Run yourself
Since until now I haven't dockerized this version you need to setup some stuff, in order to run the project:

WARNING: Ignore the steps, the README is deprecated. If you want to run the project yourself please contact me

=== Setup

* You will need: JDK(8 or 11), Maven, wget, unzip

WARNING: I recently set up a local Jenkins and couldn't get it to work under JDK 11 only a downgrade to JDK 8 seemed to
fix the issues (e.g. installing the recommended jenkins plugins correct). Which is strange because JDK 11 is explicitely
mentioned on the official Jenkins Website to work too.

WARNING: When setting up the project lately I also figured out, that if you have a JDK 15 installed, it is possible that
you have to delete the JDK 15 (only switching the JDK version didn't work for me). If the log.txt file has an error in it,
which is saying Java Version 59 not supported... something, that's probably the reason for it.

* Setup Jenkins-Runner:
** Install Local Jenkins:
*** `wget http://mirrors.jenkins.io/war-stable/latest/jenkins.war` download the latest war file of jenkins
*** `unzip jenkins.war -d /opt/jenkins` extract jenkins into tmp
*** `JENKINS_HOME=/opt/jenkins_home java -jar jenkins.war` set Jenkins Home and run Jenkins
*** go to http://localhost:8080/, follow the installation step
and install the recommended set of plugins (also change admin password)
*** install the https://plugins.jenkins.io/docker-workflow/[Docker Pipeline] Plugin (Manage Jenkins -> Plugins ...)
** Install Jenkins-Runner:
*** Download the zip file `wget https://repo.jenkins-ci.org/releases/io/jenkins/jenkinsfile-runner/jenkinsfile-runner/1.0-beta-18/jenkinsfile-runner-1.0-beta-18.zip`
*** `unzip jenkinsfile-runner-1.0-beta-18.zip -d /opt/jenkinsfile-runner` e.g. simply unzip
*** `sudo chmod +x /opt/jenkinsfile-runner/bin/jenkinsfile-runner` make executable


=== Run

1. Start the postgres database with docker. Simply type `docker-compose up postgres-db` in the root directory
2. Start the quarkus servers: go into the `backend` / `testing-api` directory and run them by
`./mvnw clean compile quarkus:dev`
3. Now you can use the Project under https://localhost:8080

Then you can run the requests.http file located in testing/http-requests but be sure to use the right ID, which can
be found in the database.

Import Database into Intellij with backend/datasource.txt file
=> Import from Clipboard => search for Example ID to test the project
User: app, Password: app

== https://github.com/jenkinsci/jenkinsfile-runner#usage-in-command-line[Jenkins-Runner]

* Usage: `jenkinsfile-runner -w <path to war> -p <path to plugins> -f <path to Jenkinsfile> [-a "param1=Hello" -a "param2=value2"]`
 e.g. ` ~/Downloads/jenkinsfile-runner-1.0-beta-18/bin/jenkinsfile-runner -w /tmp/jenkins -p /tmp/jenkins_home/plugins/ -f ./Jenkinsfile
