= Backend
Christian Donnabauer
1.0, 2020-01-06

This directory contains a Quarkus Server, which can be started by typing `./mvnw clean
compile quarkus:dev`. The Server itself listens to HTTP-Requests on Port 9090 e.g.
http://localhost:9090[]. If you want to use the debugger, it can be found at Port 5005.

== Tasks

=== Communication to Database
The first and most important task of the backend Server is the communication to the database.
Although the project contains a second Quarkus Server, everything related to the database is
handled by the Backend Server.

=== Communication via Kafka
As already said the project contains a second Quarkus Server, the Testing API. These two
Server communicate using Apache Kafka. So the Backend Server sends Kafka Messages
(Submitions) and receives Messages with the test results.

=== General Backend
This Quarkus instance also serves as a normal Backend for an Angular Frontend. So this Server
has multiple Rest Endpoints, to retrieve data. If you are interested in the Endpoints only,
go to the **http-requests** directory, which contains more detail.

=== User Management
Eventually the Backend Server should also be responsible for the User Management and
Security. Currently, the project is work in progress, so those two aspects are not as
important.
