pipeline {
  agent any
  triggers {
        cron('H/10 * * * *')
    }
  stages {
    stage('Print 10 times') {
    steps {
        sh '''#!/bin/bash
        set -ex
        echo "Hello world"
        ''' }
      }
  }
}
