= HTTP-Requests
Christian Donnabauer
1.0, 2020-01-06
:source-highlighter: rouge

:icons: font
:toc: left

This directory contains **.http** Files for the Rest Endpoints of the Backend Server. You can
execute these Files using you IDE, but be aware that some Endpoints may require preparation
e.g. other http requests before. For example you have to create an example first, before you
can test it.

NOTE: Be aware that the database currently is drop-and-create (each time you
restart the server, you need to Create and Run Examples, else the response is going
to be empty)

Also, these requests are heavily dependent on IDs, which get generated automatically. So
always have a look at the IDs in the request compared to the IDs actually in the database.

== Rest Endpoints

=== Create Example - http://localhost:9090/upload/example[]
If applied correct, an example is created, which can be attended afterwards. This Endpoint
consumes a Multipart upload containing:

[%header,cols=4*]
|===
|Name
|Content-Type
|Explanation
|Example Value

|username
|text/plain
|The name of the author of the Example
|Donnabauerc

|exampleName
|text/plain
|The name of the Example
|HelloWorld

|exampleType
|text/plain
|Definition how the example will be tested
|currently only value "MAVEN" is supported

|description
|text/plain
|Short description of the example
|The goal of this example is to create a Maven Project, which prints Hello World!

|instruction
|text/markdown
|Instruction File of the example
|# Hello World...

|pom
|text/xml
|Pom File for Maven Projects, should be changed for other possible types
|<?xml version="1.0"?...

|solution
|text/x-java
|The solution files for the Example
|package at.htl...

|test
|text/x-java
|The Unittests of the Example
|package at.htl...

|jenkinsfile
|application/octet-stream
|The Jenkinsfile used to setup the Pipeline for testing the example
|pipeline {...

|===

A Possible Output would look like this:

[source,json]
----
{
  "id": 6,
  "author": "Donnabauerc",
  "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
  "name": "Hello World",
  "type": "MAVEN"
}
----

=== Test Example - http://localhost:9090/upload/exercise[]
This endpoint tests provided code with the related Example. It also consumes a Multipart
Upload containing:

[%header,cols=4*]
|===
|Name
|Content-Type
|Explanation
|Example Value

|example
|text/plain
|The Id of the Example, which is going to be attended
|6

|username
|text/plain
|The name of the user testing the Code
|Donnabauerc


|code
|text/x-java
|The Java Files written by the user, which should be tested
|package at.htl...

|===

A possible Response would be (the Submission ID):

[source,html]
----
successfully submitted with ID 10
----

=== Create And Run Example
Simply the Combination of the other two Requests, so you can run the requests as one.

=== History of Student - http://localhost:9090/portfolio/{username}[]
Returns all the Submitions made by a specific student. In den provided example every
Submition made by **Schueler1** gets returned, but you can change the Path-Parameter
as you like.

A Possible Output would look like this:
[source, json]
----
[
  {
    "id": 8,
    "author": "Schueler1",
    "example": {
      "id": 6,
      "author": "Lehrer1",
      "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
      "name": "Example 1",
      "type": "MAVEN"
    },
    "lastTimeChanged": "2021-01-13T16:46:24.765136",
    "pathToZip": "../../projects-in-queue/project-under-test-8.zip",
    "result": "Finished: FAILURE",
    "status": "FAIL"
  },
  {
    "id": 10,
    "author": "Schueler1",
    "example": {
      "id": 6,
      "author": "Lehrer1",
      "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
      "name": "Example 1",
      "type": "MAVEN"
    },
    "lastTimeChanged": "2021-01-13T16:52:09.463372",
    "pathToZip": "../../projects-in-queue/project-under-test-10.zip",
    "result": "Finished: SUCCESS",
    "status": "SUCCESS"
  }
]
----

=== Get Example By Id - http://localhost:9090/example/{id}][]
Returns a specific Example including a files Array. Here the parameter (the id) can be changed as you like.
Currently the files are sent as text (should probably be changed in future). A sample output would look
something similar to this:

[source,json]
----
{
  "id": 6,
  "name": "Example 1",
  "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
  "author": "Lehrer1",
  "type": "MAVEN",
  "files": [
    {
      "name": "HelloWorld.java",
      "filetype": "SOLUTION",
      "content": "package at.htl.examples;\n\npublic class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}\n"
    },
    {
      "name": "HelloWorldTest.java",
      "filetype": "TEST",
      "content": "package at.htl.examples;\n\nimport org.junit.jupiter.api.AfterEach;\nimport org.junit.jupiter.api.BeforeEach;\nimport org.junit.jupiter.api.Test;\n\nimport java.io.ByteArrayInputStream;\nimport java.io.ByteArrayOutputStream;\nimport java.io.InputStream;\nimport java.io.PrintStream;\n\nimport static org.assertj.core.api.Assertions.assertThat;\n\nclass HelloWorldTest {\n\n    private final InputStream systemIn = System.in;\n    private final PrintStream systemOut = System.out;\n\n    private ByteArrayInputStream testIn;\n    private ByteArrayOutputStream testOut;\n\n    @BeforeEach\n    public void setupOutput() {\n        testOut = new ByteArrayOutputStream();\n        System.setOut(new PrintStream(testOut));\n    }\n\n    private void provideInput(String data) {\n        testIn = new ByteArrayInputStream(data.getBytes());\n        System.setIn(testIn);\n    }\n\n    private String getOutput() {\n        return testOut.toString();\n    }\n\n    @AfterEach\n    public void restoreSystemInputOutput() {\n        System.setIn(systemIn);\n        System.setOut(systemOut);\n    }\n\n    @Test\n    public void test001() {\n        final String testString = \"Hello, World!\\n\";\n        provideInput(testString);\n\n        HelloWorld.main(null);\n        assertThat(testString).isEqualTo(getOutput());\n    }\n\n}\n"
    },
    {
      "name": "instruction.md",
      "filetype": "INSTRUCTION",
      "content": "# This would be the Instruction File of an Example, written by teachers\n"
    },
    {
      "name": "Jenkinsfile",
      "filetype": "JENKINSFILE",
      "content": "pipeline {\n    agent {\n        docker {\n            image 'maven:3-alpine'\n        }\n    }\n    stages {\n        stage('Test') {\n            steps {\n                sh 'mvn test'\n            }\n        }\n    }\n}"
    },
    {
      "name": "pom.xml",
      "filetype": "POM",
      "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<project xmlns=\"http://maven.apache.org/POM/4.0.0\"\n         xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n         xsi:schemaLocation=\"http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd\">\n    <modelVersion>4.0.0</modelVersion>\n\n    <groupId>at.htl</groupId>\n    <artifactId>code-examples</artifactId>\n    <version>1.0-SNAPSHOT</version>\n    <packaging>jar</packaging>\n\n    <properties>\n        <maven.compiler.source>8</maven.compiler.source>\n        <maven.compiler.target>8</maven.compiler.target>\n    </properties>\n\n    <build>\n        <plugins>\n            <plugin>\n                <artifactId>maven-surefire-plugin</artifactId>\n                <version>3.0.0-M4</version>\n            </plugin>\n            <plugin>\n                <groupId>org.apache.maven.plugins</groupId>\n                <artifactId>maven-surefire-report-plugin</artifactId>\n                <version>3.0.0-M4</version>\n                <executions>\n                    <execution>\n                        <phase>test</phase>\n                        <goals>\n                            <goal>report-only</goal>\n                        </goals>\n                    </execution>\n                </executions>\n            </plugin>\n        </plugins>\n    </build>\n\n    <dependencies>\n        <dependency>\n            <groupId>org.junit.jupiter</groupId>\n            <artifactId>junit-jupiter</artifactId>\n            <version>5.6.2</version>\n            <scope>test</scope>\n        </dependency>\n            <dependency>\n                <groupId>org.assertj</groupId>\n                <artifactId>assertj-core</artifactId>\n                <version>3.15.0</version>\n                <scope>test</scope>\n            </dependency>\n    </dependencies>\n</project>"
    }
  ]
}
----

=== List All Examples - http://localhost:9090/example/list[]
This Endpoint returns an Array of every Example currently stored in the database. A possible Response would
look like this:

[source,json]
----

  {
    "id": 6,
    "author": "Lehrer1",
    "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
    "name": "Example 1",
    "type": "MAVEN"
  },
  {
    "id": 12,
    "author": "Lehrer1",
    "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
    "name": "Example 2",
    "type": "MAVEN"
  }
]
----

== SSE
If you submitted your project correct, you can see the status of the submition as a sse.
Simply insert the wanted Submission ID (returned by the Test Endpoint) into the link
http://localhost:9090/submission/<id>[] and open it in your Webbrowser. At this Endpoint
you can see the raw data, which would be processed with JS in an actual Frontend somewhat
like http://localhost:9090/submission.html?id={id}[].

The output of http://localhost:9090/submission/8[] for example looks something like that:
[source,html]
----
data: 17:14:03 Uhr: SUBMITTED

data: 17:15:04 Uhr: SUCCESS
----

Or http://localhost:9090/submission.html?id=8[] like:
++++
<html lang="en"><head>
    <meta charset="UTF-8">
    <title>Submition</title>

    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/css/patternfly.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/patternfly/3.24.0/css/patternfly-additions.min.css">
</head>
<body>
<div class="container">
    <h2 id="heading">Submission 8</h2>
    <div class="row">
        <p class="col-md-12"><strong><span id="content">17:15:04 Uhr: SUCCESS</span></strong></p>
    </div>
</div>
</body>
</html>
++++




