= HTTP-Requests
Christian Donnabauer
1.0, 2020-01-06
:source-highlighter: rouge

:icons: font
:toc: left


This directory contains **.http** Files for the Rest Endpoints of the Backend Server. You can
execute these Files using you IDE, but be aware that some Endpoints may require preparation
e.g. other http requests before. For example you have to create an example first, before you
can test it.

Also, these requests are heavily dependent on IDs, which get generated automatically. So
always have a look at the IDs in the request compared to the IDs actually in the database.

== Rest Endpoints

=== Create Example
This Endpoint consumes a Multipart upload containing:

[%header,cols=4*]
|===
|Name
|Content-Type
|Explanation
|Example Value

|username
|text/plain
|The name of the author of the Example
|Donnabauerc

|exampleName
|text/plain
|The name of the Example
|HelloWorld

|exampleType
|text/plain
|Definition how the example will be tested
|currently only value "MAVEN" is supported

|description
|text/plain
|Short description of the example
|The goal of this example is to create a Maven Project, which prints Hello World!

|instruction
|text/markdown
|Instruction File of the example
|# Hello World ...

|pom
|text/xml
|Pom File for Maven Projects, should be changed for other possible types
|<?xml version="1.0"?>...

|solution
|text/x-java
|The solution files for the Example
|package at.htl; ...

|test
|text/x-java
|The Unittests of the Example
|package at.htl; ...

|jenkinsfile
|application/octet-stream
|The Jenkinsfile used to setup the Pipeline for testing the example
|pipeline { ...

|===

If applied correct, a example is created, which can now be attended. A Possible Output would
like this:

[source,json]
----
{
  "id": 6,
  "author": "Donnabauerc",
  "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
  "name": "Hello World",
  "type": "MAVEN"
}
----

=== Test Example

=== Create And Run Example
Simply the Combination of the other two Requests, so you can run the requests as one.

=== History of Student

== SSE
If you submitted your project correct, you can see the status of the submition
as a sse. Simply go to http://localhost:9090/submission.html?id={id}[]. Of
course, you need to set your submitionID to see your wanted submition.


