= HTTP-Requests
Christian Donnabauer
1.0, 2020-01-06
:source-highlighter: rouge

:icons: font
:toc: left


This directory contains **.http** Files for the Rest Endpoints of the Backend Server. You can
execute these Files using you IDE, but be aware that some Endpoints may require preparation
e.g. other http requests before. For example you have to create an example first, before you
can test it.

Also, these requests are heavily dependent on IDs, which get generated automatically. So
always have a look at the IDs in the request compared to the IDs actually in the database.

== Rest Endpoints

=== Create Example
If applied correct, an example is created, which can be attended afterwards. This Endpoint
consumes a Multipart upload containing:

[%header,cols=4*]
|===
|Name
|Content-Type
|Explanation
|Example Value

|username
|text/plain
|The name of the author of the Example
|Donnabauerc

|exampleName
|text/plain
|The name of the Example
|HelloWorld

|exampleType
|text/plain
|Definition how the example will be tested
|currently only value "MAVEN" is supported

|description
|text/plain
|Short description of the example
|The goal of this example is to create a Maven Project, which prints Hello World!

|instruction
|text/markdown
|Instruction File of the example
|# Hello World...

|pom
|text/xml
|Pom File for Maven Projects, should be changed for other possible types
|<?xml version="1.0"?...

|solution
|text/x-java
|The solution files for the Example
|package at.htl...

|test
|text/x-java
|The Unittests of the Example
|package at.htl...

|jenkinsfile
|application/octet-stream
|The Jenkinsfile used to setup the Pipeline for testing the example
|pipeline {...

|===

A Possible Output would look like this:

[source,json]
----
{
  "id": 6,
  "author": "Donnabauerc",
  "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
  "name": "Hello World",
  "type": "MAVEN"
}
----

=== Test Example
This endpoint tests provided code with the related Example. It also consumes a Multipart
Upload containing:

[%header,cols=4*]
|===
|Name
|Content-Type
|Explanation
|Example Value

|example
|text/plain
|The Id of the Example, which is going to be attended
|6

|username
|text/plain
|The name of the user testing the Code
|Donnabauerc


|code
|text/x-java
|The Java Files written by the user, which should be tested
|package at.htl...

|===

A possible Response would be (the Submission ID):

----
successfully submitted with ID 10
----

=== Create And Run Example
Simply the Combination of the other two Requests, so you can run the requests as one.

=== History of Student
Returns all the Submitions made by a specific student. In den provided example every
Submition made by **Schueler1** gets returned, but you can change the Path-Parameter
as you like.

NOTE: Be aware that the database currently is drop-and-create (each time you
restart the server, you need to Create and Run Examples, else the response is going
to be empty)

A Possible Output would look like this:
[source, json]
----
[
  {
    "id": 8,
    "author": "Schueler1",
    "example": {
      "id": 6,
      "author": "Lehrer1",
      "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
      "name": "Example 1",
      "type": "MAVEN"
    },
    "lastTimeChanged": "2021-01-13T16:46:24.765136",
    "pathToZip": "../../projects-in-queue/project-under-test-8.zip",
    "result": "Finished: FAILURE",
    "status": "FAIL"
  },
  {
    "id": 10,
    "author": "Schueler1",
    "example": {
      "id": 6,
      "author": "Lehrer1",
      "description": "The goal of this example is to create a Maven Project, which prints Hello World! ",
      "name": "Example 1",
      "type": "MAVEN"
    },
    "lastTimeChanged": "2021-01-13T16:52:09.463372",
    "pathToZip": "../../projects-in-queue/project-under-test-10.zip",
    "result": "Finished: SUCCESS",
    "status": "SUCCESS"
  }
]
----

== SSE
If you submitted your project correct, you can see the status of the submition
as a sse. Simply go to http://localhost:9090/submission.html?id={id}[]. Of
course, you need to set your submitionID to see your wanted submition.


